docs/_sidebar.md, docs/changelogs/FW-v2.0.0.md, docs/kits/Golem.md, docs/kits/Raven.md, docs/kits/Slime.md, docs/technical_documentation/Damage.md, docs/technical_documentation/Gamerules.md, docs/technical_documentation/README.md
- Added documentation for gamerules.
- Added descriptions to damage types
=> Dev reimplement gamerules

docs/changelogs/FW-v2.0.0.md, docs/kits/Knight.md
#116 
Also updated grammar in 2.0.0 changelog
=> Dev 2.0.0 db refactor

docs/changelogs/FW-v2.0.0.md, docs/maps/Somber_Swamps.md
#185 
- Added changelog for new map somber swamps
=> Added somber swamps to changelog

docs/changelogs/v2.1.0.md
Add changelog note for tab updates
#154
=> Tab Updates

docs/changelogs/v2.0.1.md
=> Bug Fix #392

docs/changelogs/v2.0.1.md, docs/technical_documentation/Gamerules.md
[#403](https://github.com/Fortress-Wars/FortressWars-Plugin/issues/403)
=> Make the default gamerule the base of all other gamerules.

docs/changelogs/v2.1.0.md
PRs
https://github.com/Fortress-Wars/FortressWars-Plugin/pull/426
https://github.com/Fortress-Wars/FortressWars-Wiki/pull/52
=> Staff Chat - (2/2)

docs/changelogs/v2.1.0.md
- Updated musketeer burst mode shoot asset
- Added notes in changelog
PRs:
https://github.com/Fortress-Wars/FortressWars-Plugin/pull/431
https://github.com/Fortress-Wars/FortressWars-Wiki/pull/53
=> Update musketeer burst mode rifle itemstack #402

docs/changelogs/v2.1.0.md
- Update changelog
PRs:
https://github.com/Fortress-Wars/FortressWars-Plugin/pull/454
https://github.com/Fortress-Wars/FortressWars-Wiki/pull/56
=> Gamerule voting anytime in lobby - 2/2

docs/changelogs/v2.1.0.md
#368 
#385 
#386 
#395 
#411 
#443 
#450 
PRs:
https://github.com/Fortress-Wars/FortressWars-Plugin/pull/521
https://github.com/Fortress-Wars/FortressWars-Wiki/pull/63
=> Various 2.1.0 bug fixes - 2/2

docs/changelogs/v2.1.0.md
https://github.com/Fortress-Wars/FortressWars-Plugin/issues/349
PRs
https://github.com/Fortress-Wars/FortressWars-Plugin/pull/524
https://github.com/Fortress-Wars/FortressWars-Wiki/pull/64
=> Dev scale command - 2/2

docs/changelogs/v2.1.0.md
[#184](https://github.com/Fortress-Wars/FortressWars-Plugin/issues/184)
- Added changelog note for updating the hardcoded map list to be dynamic
PRs
https://github.com/Fortress-Wars/FortressWars-Plugin/pull/532
https://github.com/Fortress-Wars/FortressWars-Wiki/pull/67
=> Update the fw load map command - 2/2

docs/changelogs/v2.1.0.md
Added note for credits increase change
PRs:
https://github.com/Fortress-Wars/FortressWars-Plugin/pull/526
https://github.com/Fortress-Wars/FortressWars-Wiki/pull/65
=> Increased End of Game Credit Rewards - 2/2

docs/changelogs/v2.1.0.md
[#230](https://github.com/Fortress-Wars/FortressWars-Plugin/issues/230)
PRs:
https://github.com/Fortress-Wars/FortressWars-Plugin/pull/531
https://github.com/Fortress-Wars/FortressWars-Wiki/pull/66
=> Show achievement rewards - 2/2

docs/changelogs/v2.1.0.md
[#394](https://github.com/Fortress-Wars/FortressWars-Plugin/issues/394)
PRs
https://github.com/Fortress-Wars/FortressWars-Plugin/pull/549
https://github.com/Fortress-Wars/FortressWars-Wiki/pull/72
=> Dev respawn on sudden death start - 2/2

docs/changelogs/v2.1.1.md
https://github.com/Fortress-Wars/FortressWars-Plugin/pull/629
https://github.com/Fortress-Wars/FortressWars-Server/pull/34
https://github.com/Fortress-Wars/FortressWars-Wiki/pull/78
=> 2.1.1 bug fixes - 3/3

docs/changelogs/v2.1.1.md
added changelogs to the map changes for Ravine, Lazarus and Hotel Monseñor
https://github.com/Fortress-Wars/FortressWars-Plugin/pull/626
https://github.com/Fortress-Wars/FortressWars-Server/pull/33
https://github.com/Fortress-Wars/FortressWars-Wiki/pull/77
=> 2.1.1 Map updates 3/3

docs/changelogs/v2.1.1.md
- Added changelog notes for new bug fixes and demolitionist updates
https://github.com/Fortress-Wars/FortressWars-Plugin/pull/640
https://github.com/Fortress-Wars/FortressWars-Wiki/pull/81
=> 2.1.1 more bug fixes - 2/2

docs/changelogs/v2.1.1.md
Added changelog for fixing the using medic potion slowing the player down
=> Added changelog for medic item model fixes

docs/changelogs/v2.1.0.md, docs/changelogs/v2.2.0.md
- Add update to 1.21.8 to changelog
https://github.com/Fortress-Wars/FortressWars-Plugin/pull/658
https://github.com/Fortress-Wars/FortressWars-Server/pull/38
https://github.com/Fortress-Wars/FortressWars-Wiki/pull/86
=> Update to 1.21.8 - Support debugging in IntelliJ - 3/3
